### ISSUE TITLE
Creating image version without specifying max-width (original size), results in smaller image file size (lesser quality?) than a smaller px image?

### ISSUE THREAD

**Issue by Eric-Tran** [Turistforeningen/node-s3-uploader#122]
### I created an image with different versions, however the original image size (which is larger in px), is a smaller file size than an image version that is smaller in px.

* Operating system
  * [ ] Mac

* Node.js version (`node --version`)
  * [ ] Node.js v6.x

* ImageMagick version (`identify -version`)
  * [ ] ImageMagick v7.0.x

* s3-uploader version
  * [ ] v2.x

### Steps to reproduce
Resized image smaller than original produces a bigger file size than original image . Create an image size without specifying maxWidth: (i.e retain original px size). Compare that with an image with a smaller maxWidth. Original image is around 1000px.

example: 

 versions: [{
        format: 'png',
        suffix: '-orig',
        quality: 100
      },
      {
        maxWidth: 600,
        format: 'png',
        suffix: '-med',
        quality: 100
      },

This results in the -orig being a smaller filesize than -med.

-orig size ~24kb
-med size ~165kb

Expect original to be larger file size since it is a larger image. Same quality settings.

**Comment by Starefossen** [comment]
Did resolve this issue, @Eric-Tran ?

**Comment by Eric-Tran** [comment]
Yes issue has been resolved, my mistake the original image was actually smaller than the -med version.
