### ISSUE TITLE
Image resize error

### ISSUE THREAD

**Issue by jbroughton72** [Turistforeningen/node-s3-uploader#21]
Node.js v0.10.32
mageMagick v6.9.0-10
Ubuntu v14.04.1 LTS

the code for the uploader:
var uuid = require('node-uuid');
var config = require('../config');
var _ = require('underscore');
var Upload = require('s3-uploader');

module.exports = {

	connect: function() {
		var awsConfig = config.get('s3config');
		console.log(awsConfig);

		try {
			return new Upload(awsConfig.bucket, {
				url: awsConfig.url,
				aws: {
					region: awsConfig.region,
					acl: 'public-read',
					accessKeyId: awsConfig.accessKey,
					secretAccessKey: awsConfig.secretAccessKey,
					endpoint: awsConfig.url,
					s3BucketEndpoint: true
				},
				versions: [{
					original: false
				}, {
					suffix: '-large',
					quality: 80,
					maxHeight: 1040,
					maxWidth: 1040,
				}, {
					suffix: '-medium',
					maxHeight: 780,
					maxWidth: 780
				}, {
					suffix: '-small',
					maxHeight: 320,
					maxWidth: 320
				}]
			});
		} catch (e) {
			console.log('error from uploader connect', e);
		}
	},
	upload: function(file, client) {
		try {
			client.upload(file, {}, function(err, images, meta) {
				if (err) {
					console.error('Upload Error', err);
				} else {
					for (var i = 0; i < images.length; i++) {
						console.log('Thumbnail with width %i, height %i, at %s', images[i].width, images[i].height, images[i].url);
					}
				}
			});
		} catch (e) {
			console.log('error from upload', e);
		}
	}
}

In the middleware, we call execute the following:
uploader.upload(req.files.uploadedFiles.path, req.uploader);
req.uploader gets set when the application starts and it creates the connection and returns the client.

the error we see is: 
{ [Error: Command failed: convert: invalid argument for option `-resize': -auto-orient @ error/convert.c/ConvertImageCommand/2555.
] code: 1, signal: null }

any thoughts?

**Comment by Starefossen** [comment]
I'll see if I can replicate this locally...

**Comment by jbroughton72** [comment]
The issue was in   versions: {original: false) in the config. The resize code is looking for a maxWidth and a maxHeight. I removed original and it worked great.
