### ISSUE TITLE
upload options override path

### ISSUE THREAD

**Issue by jbroughton72** [Turistforeningen/node-s3-uploader#22]
Is it possible to have the 'path' config option to be overridden when an upload takes place?
ie:
client.upload(file, {path: 'imagesJanuary/'}, function(err, images, meta) {...
client.upload(file, {path: 'imagesFebruary/'}, function(err, images, meta) {...

thanks
Jason

**Comment by Starefossen** [comment]
I have implemented this as `awsPath: "some/new/path/"` which will be out in the next release of s3-uploader.

**Comment by jbroughton72** [comment]
Awesome, Thank you soo much! Cheers!!
