### ISSUE TITLE
Error code:4

### ISSUE THREAD

**Issue by fabiusss** [Turistforeningen/node-s3-uploader#25]
Hi,
I have the following error:

     { [Error: Command failed: Parametro non valido - server\uploads\86caf0d05da8d7fa
     c0fc964368a44939.jpg.mpc
     ] code: 4, signal: null }

In folder server\uploads\ there is the file: 86caf0d05da8d7fac0fc964368a44939.jpg

In myBucket no file is uploaded.

my configuration is:

    var client = new Upload('myBucket', {
    aws:{
      region: 'eu-west-1',
      acl: 'public-read',
      accessKeyId:'XXXXXXXXXXXXXX',
      secretAccessKey:'XXXXXXXXXXXXXXXXXXX'
    },
    versions: [{
      original: true
    },{
      suffix: '-large',
      quality: 80,
      maxHeight: 1040,
      maxWidth: 1040,
    },{
      suffix: '-medium',
      maxHeight: 780,
      maxWidth: 780
     },{
      suffix: '-small',
      maxHeight: 320,
      maxWidth: 320
     }]
    });

    var filePath='server\uploads\346edfc4433be42e5b85e9927f41b0cf.jpg';

    client.upload(filePath, {}, function(err, images, meta) {
      if (err) {
        console.error(err);
      } else {
        for (var i = 0; i < images.length; i++) {
          console.log('Thumbnail with width %i, height %i, at %s', images[i].width, images[i].height, images[i].url);
        }
      }
    });

**Comment by Starefossen** [comment]
Hi @fabiusss,

Can you post some details about the machine/server you are experiencing these issues with? From your file paths it looks like your on a Windows machine, is that correct?

**Comment by fabiusss** [comment]
It is, for development use with Windows 8.1 pro with NWM (https://nwm.julianxhokaxhiu.com/).
If you need more details please ask.

**Comment by fabiusss** [comment]
Hi @Starefossen,
I tested my app also in Ubuntu 14.04 x64 and i have the following error:

      { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

**Comment by Starefossen** [comment]
Did you ever solve this error @fabiusss?

Could you post the output of the following command: 

```
identify --version
```
