### ISSUE TITLE
cleanup does nothing

### ISSUE THREAD

**Issue by mcassagnes** [Turistforeningen/node-s3-uploader#35]
The option to cleanup both original and resized images does not work. In fact there's no reference to it in the code. Am I missing something ?

**Comment by Starefossen** [comment]
The `cleanup` option is a v1.0 feature (currently v1.0.0-rc.4). Documentation for s3-uploader v0.9 can be found here: https://github.com/Turistforeningen/node-s3-uploader/blob/stable/0.x/README.md
