### ISSUE TITLE
Force type of image, but not work

### ISSUE THREAD

**Issue by nicholasess** [Turistforeningen/node-s3-uploader#37]
I set in object opts, but create just image with type `.jpg`.

My code:
```
versions: [{
    maxHeight: 270,
    maxWidth: 310,
    suffix: '-small',
    quality: 100,
    format: 'png'
  }]
```
result: 
```
{ quality: 100,
    format: 'jpeg',
    src: '/tmp/gm-e7cf903cd727e32e1097dfd5ca9a55eee94fc8cf-small.jpeg',
    width: 310,
    height: 270,
    etag: 'adcc36a20b17c0053ba7ef987b6c37c5',
    path: 'track_cover/hb/yF/tY-small.jpeg',
    url: 'https://s3.amazonaws.com/welearnfs/track_cover/hb/yF/tY-small.jpeg' }
```

**Comment by Starefossen** [comment]
You need to install the v1.x version (release candidate 10) to get forced format to work:

```
npm install s3-uploader@1.0.0-rc.10
```

**Comment by nicholasess** [comment]
Need change how to use function upload?
Because when i change the version and executa a file with code, return erro.
```
{ [InvalidArgument: null]
  message: null,
  code: 'InvalidArgument',
  time: Tue Jul 21 2015 13:55:02 GMT-0300 (BRT),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }
```

**Comment by Starefossen** [comment]
You can look over the list of breaking changes [here](https://github.com/Turistforeningen/node-s3-uploader/releases/tag/v1.0.0-rc.1). There are some changes to the configuration when you instantiate the `Uploader` class.

**Comment by nicholasess** [comment]
@Starefossen i follow the changes, but return other error.

"errTimeoutError: Missing credentials in config"

Code:
```
var client = new Upload(S3_BUCKET, {
  awsBucketRegion: 'us-east-1',
  awsBucketPath: 'track_cover/',
  awsBucketAcl: 'public-read',
  awsAccessKeyId: S3_KEY,
  awsSecretAccessKey: S3_SECRET,
  awsMaxRetries: 2,
  awsHttpTimeout: 3000,
  tmpDir: "",
  resizeQuality: 100, 
  cleanup: {
    versions: false,
    original: false
  },
  original: {
    awsImageAcl: 'public'
  },
  resize: {
    quality: 100
  },
  versions: [{
    maxHeight: 270,
    maxWidth: 310,
    suffix: '-small',
    format: 'png'
  }]
});
```

**Comment by Starefossen** [comment]
Can you post the following and I will try to debug this for you:

* What operating system and version are you using
* What version of node/iojs are you using?
* What version of ImageMagick are you using?

**Comment by nicholasess** [comment]
Elementary OS Freya
node: v0.10.37
ImageMagick 6.7.7-10

**Comment by Starefossen** [comment]
Yeah, you should upgrade your version of ImageMagick. I also noticed that you have not updated your AWS configuration to match the new format:

```
var client = new Upload(S3_BUCKET, {
  was: {
    region: 'us-east-1',
    path: 'track_cover/',
    acl: 'public-read',
    accessKeyId: S3_KEY,
    secretAccessKey: S3_SECRET,
    awsMaxRetries: 2,
    httpOptions: {
      timeout: 3000
    }
  }
  ...
});
```

**Comment by klindberg** [comment]
I had the same problem with image types, '.png' especially. I upgraded to version 1.0.0-rc.10 per your comment above and it solved the problem!

I wanted to especially thank you for this node-s3-uploader! I had been using s3FS to upload (worked fine) but after a lot of time researching, I could not figure out how to resize the images during upload. Node-s3-uploaded handles that so well and so easily!

Thank you!
Ken

**Comment by Starefossen** [comment]
Thanks for the kind words @klindberg! I will push forward to get v1.0.0 released; we have been using it in production for a while now with no known bugs as of the latest RC version.

**Comment by anthonyringoet** [comment]
I've been using the different release candidates in production as well.

**Comment by nicholasess** [comment]
I could not change the version of imagemagick, then i'll use the trivial proccess that i'm using.
But when I can change , I will use the s3 - uploader.

Thanks for the your attention!
