### ISSUE TITLE
How to pipe a path of multipart data? 

### ISSUE THREAD

**Issue by nikkwong** [Turistforeningen/node-s3-uploader#42]
It is not instantly apparent to me. Thanks.

**Comment by Starefossen** [comment]
Piping is currently not possible because of the way we use `ImageMagic`. Your only option is to pipe the image to a file and `s3-uploader` can be configured to remove the image on disk for you when it is done resizing and uploading.

**Comment by nikkwong** [comment]
Great! Thanks for the info!
