### ISSUE TITLE
Use greenkeeper.io for keeping dependencies up to date

### ISSUE THREAD

**Issue by anthonyringoet** [Turistforeningen/node-s3-uploader#54]
Let's automate the boring part. :smile: 
Agree/disagree?

http://greenkeeper.io
> It knows when your dependencies got updated and simply sends you a pull request with the new package.json.

> Should a new version inside your existing version range cause your build to fail, we’ll let you know immediately.

> If you’ve got continuous integration tests, they’ll run, and you can keep your software up to date with a single click on GitHub’s merge button.

**Comment by anthonyringoet** [comment]
@Starefossen What do you think?

**Comment by Starefossen** [comment]
I think we should set it up. Are you able to do it yourself or do I have to do it?

**Comment by anthonyringoet** [comment]
Anyone with the valid access rights can do it I think. I'll check it out :)

**Comment by Starefossen** [comment]
Great! If it is successful feel free to set it up for the other repositories as well:

* https://github.com/Turistforeningen/node-im-metadata
* https://github.com/Turistforeningen/node-im-resize
* https://github.com/Turistforeningen/node-aspectratio

**Comment by anthonyringoet** [comment]
Currently only actual admins can enable repo's on greenkeeper. This will possibly be changed in the future.

https://github.com/greenkeeperio/greenkeeper/issues/48#issuecomment-146693583

**Comment by Starefossen** [comment]
Finally got around to do this. Sorry for the long wait.
