### ISSUE TITLE
Configuire cloudFront for AWS-SDK

### ISSUE THREAD

**Issue by damonYuan** [Turistforeningen/node-s3-uploader#61]
how to Configuire cloudFront for AWS-SDK?

**Comment by Starefossen** [comment]
Hi Damon,

I have not tried to use `s3-uploader` with CloudFront. You can add your own [custom AWS configurations](https://github.com/Turistforeningen/node-s3-uploader#aws-note) and from aws/aws-sdk-js#669 it looks like you could do it like this: 

```
process.env. AWS_ACCESS_KEY_ID = '*****';
process.env. AWS_SECRET_ACCESS_KEY = '*****';

var client = new Upload('my_s3_bucket', {
  aws: {
    path: 'images/',
    endpoint: 'XXXXXXXX.cloudfront.net',
    s3BucketEndpoint: true,
    region: 'us-east-1',
  },
  versions: […]
});
```

**Comment by damonYuan** [comment]
let me try it and will let you know the result soon. Thanks for your reply

**Comment by Starefossen** [comment]
Did it work @damonYuan, if so, can you close this issue?

**Comment by damonYuan** [comment]
hi Starefossen, it works! Thanks!
