### ISSUE TITLE
'starefossen/rand-path' is not in the npm registry

### ISSUE THREAD

**Issue by kiro112** [Turistforeningen/node-s3-uploader#62]
npm WARN package.json cluster@0.7.7 cluster is also the name of a node core module.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'starefossen/rand-path' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 's3-uploader'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "s3-uploader"
npm ERR! cwd /home/ubuntu/web-service-api-v2
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

node version 0.10.33
npm version 1.4.28

**Comment by Starefossen** [comment]
Hmmm... This has to do with the fact that `@starefossen/rand-path` is a [scoped package](https://docs.npmjs.com/getting-started/scoped-packages). 

* Which npm registry are you installing from? Have you configured something in your `.npmrc`?
* Your Node.js/NPM version are kind of old, can you alt least upgrade `npm install -g npm`?
* What does `npm install --verbose @starefossen/rand-path` output?
* What does `npm install --verbose s3-uploader@2.0.0-rc.1` output?

**Comment by kiro112** [comment]
Which npm registry are you installing from? Have you configured something in your .npmrc?
   - No, havent changed anything.
Your Node.js/NPM version are kind of old, can you alt least upgrade npm install -g npm?
    - cant upgrade right now, but will do on future days
What does npm install --verbose @starefossen/rand-path output?
What does npm install --verbose s3-uploader@2.0.0-rc.1 output?
    -http://pastebin.com/6WHNMiwq

**Comment by anthonyringoet** [comment]
Is it possible you need an npm version of min 2.7.0 to use scoped packages?
https://docs.npmjs.com/getting-started/scoped-packages#update-npm-and-log-in

**Comment by Starefossen** [comment]
Yes, I think so too. The npm docs do not specify if this version is the required version for installing or just publishing scoped packages.

**Comment by anthonyringoet** [comment]
@kiro112 Is your issue fixed? If not, could you try with an updated npm version?

**Comment by Philip-Nunoo** [comment]
Just got this issue noticed my npm -v was behind.
Upgraded it to 3.5.2 and everything works fine> :)
[sudo] npm install npm@latest -g

**Comment by anthonyringoet** [comment]
Nice, thanks for the follow-up.
