### ISSUE TITLE
Drop support for Node.js v0.10

### ISSUE THREAD

**Issue by Starefossen** [Turistforeningen/node-s3-uploader#63]
I think we should discontinue support for Node.js v0.10, as mentioned below this version of Node.js is officially discontinued after October 1st 2016.

**From [nodejs/lts](https://github.com/nodejs/lts#example) repo:**

> 1. nodejs/node v4.2.0 becomes the current LTS Release
> 2. joyent/node v0.10 continues in Maintenance only mode until October 1st, 2016
> 3. joyent/node v0.12 continues as LTS until April 1st, 2016, after which it moves into Maintenance only mode until April 1st, 2017.
> 4. On or around October 1st, 2016, the second LTS Release from the converged is cut.
> 5. LTS for v4.2.0 continues until April 1st, 2017, after which it moves to Maintenance mode until around April 1st, 2017.
> 6. On or around October 1st, 2017, the third LTS Release from the converged is cut.

**Comment by anthonyringoet** [comment]
Agree to follow the Node guidelines. People on 0.10.x can still use it, albeit without support.
