### ISSUE TITLE
Renaming of file - what happens?

### ISSUE THREAD

**Issue by latitudehopper** [Turistforeningen/node-s3-uploader#65]
Apologies if this is mentioned somewhere, I have looked and cannot see it.
When "image.jpg" is uploaded is the name retained in the object but with the suffix appended? The example show is being returned as a long string but I cannot see where this has come from.

**Comment by Starefossen** [comment]
Good question @latitudehopper, this should definitely be explained better in the docs!

By default uploaded images get assigned a unique random name like `110ec58a-a0f2-4ac4-8393-c866d813b8d1` using the UUID v4 algorithm. All resized versions of this image will have a suffix string appended to them like this: `110ec58a-a0f2-4ac4-8393-c866d813b8d1-small`.

This is configurable, you can use another random name generator of your choosing:

```js
var client = new Upload(process.env.AWS_BUCKET_NAME, {
  randomPath: require('@starefossen/rand-path')
});
```

or you can set the name for the uploaded image yourself:

```js
client.upload(file, { path: 'my-file-name' }, function(err, versions, meta) {
  // uploaded image is here
});
```

**Comment by latitudehopper** [comment]
Excellent answer. Many thanks. I will have a play! Thanks, @Starefossen
