### ISSUE TITLE
Throwing error while uploading image

### ISSUE THREAD

**Issue by kantaharikrishna** [Turistforeningen/node-s3-uploader#66]
client.upload('https://s3.amazonaws.com/yadva/uploads/images/mailer_footer.jpg', {}, function(err, versions, meta) {
  if (err) { throw err; }
 
  versions.forEach(function(image) {
    console.log(image.width, image.height, image.url);
    // 1234 4567 https://my-bucket.s3.amazonaws.com/path/ab/cd/ef.jpg 
  });
  res.redirect('back');
});

I'm not able to upload images. Its always throwing error. Please help me on this.

**Comment by Starefossen** [comment]
Hi @kantaharikrishna and thanks for using s3-uploader!

For future reference, when reporting errors please also write the following information:

* Operating System
* Node.js version
* ImageMagic version

The complete configuration would also be nice as well as the actual error message reported from s3-uploader.

In this case I can tell you right away what the problem is. The image you are trying to upload is an external image and this library only supports uploading local images which are on the same disk as your application.

**Comment by kantaharikrishna** [comment]
Oh I see. I will check it.
Thank you very much for your response.

**Comment by kantaharikrishna** [comment]
Facing the same Issue:

OS: Windows 7, 32-bit
Node: 0.12.0
Imagemagick: 6.9.0


client.upload('/uploads/site-logo.png', {}, function(err, versions, meta) {
                  if (err) { throw err; }

                  versions.forEach(function(image) {
                    console.log(image.width, image.height, image.url);
                    // 1234 4567
https://my-bucket.s3.amazonaws.com/path/ab/cd/ef.jpg
                  });
  });


[image: Inline image 1]

On Sun, Dec 13, 2015 at 9:42 PM, hari krishna <kantaharikrishna@gmail.com>
wrote:

> Oh I see. I will check it.
> Thank you very much for your response.
> On 13 Dec 2015 21:38, "Hans Kristian Flaatten" <notifications@github.com>
> wrote:
>
>> Hi @kantaharikrishna <https://github.com/kantaharikrishna> and thanks
>> for using s3-uploader!
>>
>> For future reference, when reporting errors please also write the
>> following information:
>>
>>    - Operating System
>>    - Node.js version
>>    - ImageMagic version
>>
>> The complete configuration would also be nice as well as the actual error
>> message reported from s3-uploader.
>>
>> In this case I can tell you right away what the problem is. The image you
>> are trying to upload is an external image and this library only supports
>> uploading local images which are on the same disk as your application.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Turistforeningen/node-s3-uploader/issues/66#issuecomment-164271217>
>> .
>>
>


-- 
Thanks,
Harikrishna Kanta
