### ISSUE TITLE
Please help me on this.

### ISSUE THREAD

**Issue by kantaharikrishna** [Turistforeningen/node-s3-uploader#67]
OS: Windows 7, 32-bit
Node: 0.12.0
Imagemagick: 6.9.0

```js
client.upload('/uploads/site-logo.png', {}, function(err, versions, meta) {
                  if (err) { throw err; }
                 
                  versions.forEach(function(image) {
                    console.log(image.width, image.height, image.url);
                  });
                });
```

Please help me on this.

**Comment by Starefossen** [comment]
What does the error message say?

**Comment by kantaharikrishna** [comment]
if (err) { throw err; }
                                   ^
ChildProcess.exithandler (child_process.js:744:12),ChildProcess.emit
(events.js:110:17),maybeClose
(child_process.js:1008:16),Process.ChildProcess._handle.on
exit (child_process.js:1080:5)

On Sun, Dec 13, 2015 at 10:58 PM, Hans Kristian Flaatten <
notifications@github.com> wrote:

> What does the error message say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Turistforeningen/node-s3-uploader/issues/67#issuecomment-164278914>
> .
>



-- 
Thanks,
Harikrishna Kanta

**Comment by kantaharikrishna** [comment]
Please find the below error:


{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "convert
uploads/site-logo.png -auto-orient -strip -write mpr:uploads/site-logo.png
+delete mpr:u
ploads/site-logo.png -quality 80 -resize "1040x1040" -write
uploads\site-logo-large.jpg +delete mpr:uploads/site-logo.png -quality 70
-crop "NaNxNaN+NaN+NaN"
 -resize "780" -write uploads\site-logo-medium.png +delete
mpr:uploads/site-logo.png -quality 70 -crop "NaNxNaN+NaN+NaN" -resize "320"
-write uploads\site-lo
go-small.png +delete mpr:uploads/site-logo.png -quality 70 -crop
"NaNxNaN+NaN+NaN" -resize "x100" -write uploads\site-logo-thumb1.png
+delete mpr:uploads/sit
e-logo.png -quality 70 -crop "NaNxNaN+NaN+NaN" -resize "250x250"
uploads\site-logo-thumb2.png"
convert.exe: invalid argument for option `-crop': NaNxNaN+NaN+NaN @
error/convert.c/ConvertImageCommand/1156.
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "convert uploads/site-logo.png
-auto-orient -strip -write mpr:uploads/site-logo.png +delete
mpr:uploads/site-log
o.png -quality 80 -resize "1040x1040" -write uploads\\site-logo-large.jpg
+delete mpr:uploads/site-logo.png -quality 70 -crop "NaNxNaN+NaN+NaN"
-resize "780"
 -write uploads\\site-logo-medium.png +delete mpr:uploads/site-logo.png
-quality 70 -crop "NaNxNaN+NaN+NaN" -resize "320" -write
uploads\\site-logo-small.png
 +delete mpr:uploads/site-logo.png -quality 70 -crop "NaNxNaN+NaN+NaN"
-resize "x100" -write uploads\\site-logo-thumb1.png +delete
mpr:uploads/site-logo.png
-quality 70 -crop "NaNxNaN+NaN+NaN" -resize "250x250"
uploads\\site-logo-thumb2.png"' }
d:\Hari\node\yadva\application\controllers\help_desk.js:229
                  versions.forEach(function(image) {
                          ^
d:\Hari\node\yadva\application\controllers\help_desk.js:229:27,d:\Hari\node\yadva\node_modules\s3-uploader\lib\index.js:126:12,d:\Hari\node\yadva\node_module
s\s3-uploader\node_modules\async\lib\async.js:52:16,d:\Hari\node\yadva\node_modules\s3-uploader\node_modules\async\lib\async.js:543:21,d:\Hari\node\yadva\nod
e_modules\s3-uploader\node_modules\async\lib\async.js:173:37,d:\Hari\node\yadva\node_modules\s3-uploader\node_modules\im-resize\index.js:12:21,ChildProcess.e
xithandler (child_process.js:751:5),ChildProcess.emit
(events.js:110:17),maybeClose
(child_process.js:1008:16),Process.ChildProcess._handle.onexit (child_pro
cess.js:1080:5)


On Sun, Dec 13, 2015 at 11:02 PM, hari krishna <kantaharikrishna@gmail.com>
wrote:

>                   if (err) { throw err; }
>                                    ^
> ChildProcess.exithandler (child_process.js:744:12),ChildProcess.emit
> (events.js:110:17),maybeClose
> (child_process.js:1008:16),Process.ChildProcess._handle.on
> exit (child_process.js:1080:5)
>
> On Sun, Dec 13, 2015 at 10:58 PM, Hans Kristian Flaatten <
> notifications@github.com> wrote:
>
>> What does the error message say?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Turistforeningen/node-s3-uploader/issues/67#issuecomment-164278914>
>> .
>>
>
>
>
> --
> Thanks,
> Harikrishna Kanta
>



-- 
Thanks,
Harikrishna Kanta

**Comment by kantaharikrishna** [comment]
Issue resolved.

Thank you.

**Comment by shravanjha** [comment]
I am having the same issue. How did you solve this?

**Comment by jlissner** [comment]
@kantaharikrishna would you mind letting myself and @shravanjha know how you resolved the issue? I am having the same issue.

-Thanks.
Joe

**Comment by kantaharikrishna** [comment]
@jlissner @shravanjha options for the Upload class for the updated version has been changed and those changes seems not been updated on document. It's better you contact the author for proper documentation for a required package version.

**Comment by kkesley** [comment]
hi @kantaharikrishna how do you resolve this issue? I'm having the exact same issue.. What do you change in the upload class if I may ask?

**Comment by gzurbach** [comment]
In case it helps anyone: I fixed this issue by making sure that the file name passed to `client.upload()` has an extension. My file was named `/tpm/foo/random-name-with-no-enxtension` - renaming it with a `.jpg` at the end fixed the issue.
