### ISSUE TITLE
Which one is correct? It's very confusing.

### ISSUE THREAD

**Issue by kantaharikrishna** [Turistforeningen/node-s3-uploader#68]
Which set is correct from below?

awsBucketRegion: 'us-east-1',
  awsBucketPath: 'images/',
  awsBucketAcl: 'public-read',

OR

aws: {
    path: 'images/',
    region: 'us-east-1',
    acl: 'public-read'
  }

Which link from below do we need to follow?
https://github.com/Turistforeningen/node-s3-uploader/blob/stable/0.x/README.md

OR

https://www.npmjs.com/package/s3-uploader

**Comment by Starefossen** [comment]
It depends on which version of `s3-uploader` your at:

* v0.x: https://github.com/Turistforeningen/node-s3-uploader/blob/stable/0.x/README.md
* v1.x: https://github.com/Turistforeningen/node-s3-uploader/blob/stable/1.x/README.md
* v2.x: https://github.com/Turistforeningen/node-s3-uploader/blob/master/README.md
