### ISSUE TITLE
awsBucketAcl: 'public-read' in not making the resource public. Its still private.

### ISSUE THREAD

**Issue by kantaharikrishna** [Turistforeningen/node-s3-uploader#69]
awsBucketAcl: 'public-read'

Which is not making my attachment public. What is the reason for this?
version: s3-uploader@1.1.0

Please reply me on this.

**Comment by Starefossen** [comment]
Please post the following information in order for me to best help you with this problem:

* Operating System
* Node.js version
* ImageMagic version

I also need the `s3-uploader` configuration so that I can verify that you are using the correct configuration for the installed version.

**Comment by kantaharikrishna** [comment]
OS: Windows 7, 32-bit
Node: 0.12.0
Imagemagick: 6.9.0

s3-uploader@1.1.0

On Wed, Dec 16, 2015 at 11:55 AM, Hans Kristian Flaatten <
notifications@github.com> wrote:

> Please post the following information in order for me to best help you
> with this problem:
>
>    - Operating System
>    - Node.js version
>    - ImageMagic version
>
> I also need the s3-uploader configuration so that I can verify that you
> are using the correct configuration for the installed version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Turistforeningen/node-s3-uploader/issues/69#issuecomment-165013479>
> .
>



-- 
Thanks,
Harikrishna Kanta

**Comment by kantaharikrishna** [comment]
var Upload = require('s3-uploader');
var client = new Upload('my_bucket', {
  awsBucketRegion: 'us-east-1',
  awsBucketPath: 'uploads/',
  awsBucketAcl: 'public-read',

  versions: [{
    original: true
  },{
    suffix: '-large',
    quality: 80,
    maxHeight: 1040,
    maxWidth: 1040,
  },{
    suffix: '-medium',
    maxHeight: 780,
    maxWidth: 780
  },{
    suffix: '-small',
    maxHeight: 320,
    maxWidth: 320
  },{
    suffix: '-thumb',
    maxWidth: 64,
    maxHeight: 64,
    crop: {
      x: 20,
      y: 35,
      width: 100,
      height: 100
    }
  }]
});

On Wed, Dec 16, 2015 at 11:58 AM, hari krishna <kantaharikrishna@gmail.com>
wrote:

> OS: Windows 7, 32-bit
> Node: 0.12.0
> Imagemagick: 6.9.0
>
> s3-uploader@1.1.0
>
> On Wed, Dec 16, 2015 at 11:55 AM, Hans Kristian Flaatten <
> notifications@github.com> wrote:
>
>> Please post the following information in order for me to best help you
>> with this problem:
>>
>>    - Operating System
>>    - Node.js version
>>    - ImageMagic version
>>
>> I also need the s3-uploader configuration so that I can verify that you
>> are using the correct configuration for the installed version.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Turistforeningen/node-s3-uploader/issues/69#issuecomment-165013479>
>> .
>>
>
>
>
> --
> Thanks,
> Harikrishna Kanta
>



-- 
Thanks,
Harikrishna Kanta

**Comment by Starefossen** [comment]
For `s3-uploader@1.1.0` your AWS configuration needs to be like this:

```js
var client = new Upload('my_s3_bucket', {
  aws: {
    path: 'images/',
    region: 'us-east-1',
    acl: 'public-read'
  },
  ...
```

**Comment by kantaharikrishna** [comment]
Documents are very confusing..

*Documentation for s3-uploader@1.1 can be found here
<https://github.com/Turistforeningen/node-s3-uploader/blob/stable/1.x/README.md>.*
*on clicking link its taking to 0.9 version documentation.*

On Wed, Dec 16, 2015 at 12:05 PM, Hans Kristian Flaatten <
notifications@github.com> wrote:

> For s3-uploader@1.1.0 your AWS configuration needs to be like this:
>
> var client = new Upload('my_s3_bucket', {
>   aws: {
>     path: 'images/',
>     region: 'us-east-1',
>     acl: 'public-read'
>   },
>   ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Turistforeningen/node-s3-uploader/issues/69#issuecomment-165014583>
> .
>



-- 
Thanks,
Harikrishna Kanta

**Comment by kantaharikrishna** [comment]
please provide me clear link to follow for version 1.1.0

Where I can get the options for creating *Upload *object.

On Wed, Dec 16, 2015 at 12:09 PM, hari krishna <kantaharikrishna@gmail.com>
wrote:

> Documents are very confusing..
>
> *Documentation for s3-uploader@1.1 can be found here
> <https://github.com/Turistforeningen/node-s3-uploader/blob/stable/1.x/README.md>.*
> *on clicking link its taking to 0.9 version documentation.*
>
> On Wed, Dec 16, 2015 at 12:05 PM, Hans Kristian Flaatten <
> notifications@github.com> wrote:
>
>> For s3-uploader@1.1.0 your AWS configuration needs to be like this:
>>
>> var client = new Upload('my_s3_bucket', {
>>   aws: {
>>     path: 'images/',
>>     region: 'us-east-1',
>>     acl: 'public-read'
>>   },
>>   ...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Turistforeningen/node-s3-uploader/issues/69#issuecomment-165014583>
>> .
>>
>
>
>
> --
> Thanks,
> Harikrishna Kanta
>



-- 
Thanks,
Harikrishna Kanta

**Comment by Starefossen** [comment]
This is the documentation for v1.1.0: https://github.com/Turistforeningen/node-s3-uploader/blob/stable/1.x/README.md#new-uploadstring-awsbucketname-object-opts
