### ISSUE TITLE
alternative for the resize an image

### ISSUE THREAD

**Issue by EdQL** [Turistforeningen/node-s3-uploader#75]
it is possible to make the resize an image that is stored on aws. I have this code that run from another application

var im = require('imagemagick');
var Upload = require('s3-uploader

--config
var client = new Upload('bucket', {

  aws: {
    region: 'us-west-1',
    path: 'imgnormal/',
    acl: 'public-read',
    accessKeyId: 'KeyID',
    secretAccessKey: 'AK',
    endpoint: 'https://s3-us-west-1.amazonaws.com',
    },cleanup: {
      versions: false,
      original: false
    },
    original: {
      awsImageAcl: 'public'
    },
    resize: {
      quality: 100
    },
    versions: [{
      maxWidth: 780,
      aspect: '3:2!h',
      suffix: '-medium'
    },{
      maxWidth: 320,
      aspect: '16:9!h',
      suffix: '-small'
    }]

});

app.post('/resizeImg',function(req,res){

    client.upload('https://s3-us-west-1.amazonaws.com/bucket/imgnormal/house.jpeg', {}, function(err, versions, meta) {

    if (err) {
      console.log('----Nope---------', err.message);
      return res.status(400).send('NO');
    }
    console.log('----Success----', versions, data);
    return res.status(200).send('YES');

    });

});

when I executo the petition I have the following error

convert.im6: unable to open image `https:/s3-us-west-1.amazonaws.com/bucket/imgnormal/house.jpeg': No such file or directory @ error/blob.c/OpenBlob/2638

what am I doing wrong?

**Comment by anthonyringoet** [comment]
s3-uploader creates variants of a certain image at the local file system and they are uploaded to aws afterwards.
It seems you are trying to use an image that is already on aws to feed into s3-uploader's input.
Also, you don't need to explicitly require imagemagick. It should be installed.
