### ISSUE TITLE
TimeoutError: Missing credentials in config

### ISSUE THREAD

**Issue by pieterbergmans** [Turistforeningen/node-s3-uploader#95]
### Subject of the issue
I'm receiving the following error...TimeoutError: Missing credentials in config. 

The code seems to execute but, instead of the files being saved to S3, the files are saved locally.  From what I've googled, it may be related to a timing out on S3's end. Could this be and has it happened to any others?  Uploading images to S3 via other methods works just fine.  The code I'm using is verbatim from the examples posted here on github.

### Your environment
* Operating system (Mac)
* Node.js version (`6.3.1`)
* ImageMagick version (`6.9.5-3`)
* s3-uploader version (2.0.1)

**Comment by Starefossen** [comment]
Hi @pieterbergmans and sorry for the trouble you are having with s3-uploader.

It looks like we managed to remove the S3 authentication documentation from the README in the 1.x => 2.0 rewrite. You need to authenticate with AWS in one of the following ways in order for ±s3-uploader` to upload correctly to AWS S3:

**Environment variables:**

* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`

**Constructor options:**

```js
new Upload(..., {
  aws: {
    ...,
    secretAccessKey: 'SECRET_ACCESS_KEY_HERE',
    accessKeyId: 'ACCESS_KEY_ID_HERE',
  },
  ...
});

**Comment by pieterbergmans** [comment]
Hi @Starefossen ...thanks for the quick reply.  I am using the second method you mentioned.  Here is a console.log() of my config...

`
Upload {
  opts: 
   { aws: 
      { path: '',
        accessKeyId: 'AasdfM5K5LDYI2FLAQ',
        secretKeyId: 'asdfx+asfg1WtIL6lHncF4OlzQAWwh0',
        region: 'us-west-2',
        acl: 'public-read',
        httpOptions: [Object],
        maxRetries: 3,
        params: [Object],
        sslEnabled: true },
     cleanup: { versions: true, original: true },
     original: { awsImageAcl: 'public-read' },
     versions: [ [Object] ],
     returnExif: false,
     resize: { quality: 70 },
     url: 'https://s3-us-west-2.amazonaws.com/my-s3-bucket/' },
  _randomPath: 
   { [Function: v4]
     v1: [Function: v1],
     v4: [Circular],
     parse: [Function: parse],
     unparse: [Function: unparse],
     BufferClass: 
      { [Function: Buffer]
        poolSize: 8192,
        from: [Function],
        alloc: [Function],
        allocUnsafe: [Function],
        allocUnsafeSlow: [Function],
        isBuffer: [Function: isBuffer],
        compare: [Function: compare],
        isEncoding: [Function],
        concat: [Function],
        byteLength: [Function: byteLength] },
     _rng: [Function],
     _mathRNG: undefined,
     _nodeRNG: [Function],
     _whatwgRNG: undefined },
  s3: 
   Service {
     config: 
      Config {
        credentials: null,
        credentialProvider: [Object],
        region: 'us-west-2',
        logger: null,
        apiVersions: {},
        apiVersion: null,
        endpoint: 's3-us-west-2.amazonaws.com',
        httpOptions: [Object],
        maxRetries: 3,
        maxRedirects: 10,
        paramValidation: true,
        sslEnabled: true,
        s3ForcePathStyle: false,
        s3BucketEndpoint: false,
        s3DisableBodySigning: true,
        computeChecksums: true,
        convertResponseTypes: true,
        correctClockSkew: false,
        customUserAgent: null,
        dynamoDbCrc32: true,
        systemClockOffset: 0,
        signatureVersion: 's3',
        signatureCache: true,
        retryDelayOptions: [Object],
        useAccelerateEndpoint: false,
        path: '',
        accessKeyId: 'AasdfM5K5LDYI2FLAQ',
        secretKeyId: 'asdf9Vx+asdf1SZ46g1WtIL6lHasdflzQAWwh0',
        acl: 'public-read',
        params: [Object] },
     isGlobalEndpoint: false,
     endpoint: 
      Endpoint {
        protocol: 'https:',
        host: 's3-us-west-2.amazonaws.com',
        port: 443,
        hostname: 's3-us-west-2.amazonaws.com',
        pathname: '/',
        path: '/',
        href: 'https://s3-us-west-2.amazonaws.com/' },
     _clientId: 1 } }
`

**Comment by Starefossen** [comment]
Could you try changing `secretKeyId` to `secretAccessKey`, and see if that works better.

**Comment by pieterbergmans** [comment]
Wow, I feel like such an idiot. I'm not sure where I got secretKeyId from. Thanks for the help!

**Comment by Starefossen** [comment]
I am always happy to help, and I hope you'll enjoy this library 😄
